## **Logistic Regression**


*   이진(다중)분류를 위해 사용됨
*   Linear Regression -> Active Function(sigmoid/softmax) -> probability 



## **데이터 확인**

In [1]:
import numpy as np
import pandas as pd
fish=pd.read_csv("https://bit.ly/fish_csv_data")
print(fish.head()) # 데이터 상단 출력 
print(fish.tail()) # 데이터 하단 출력

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340
    Species  Weight  Length  Diagonal  Height   Width
154   Smelt    12.2    12.2      13.4  2.0904  1.3936
155   Smelt    13.4    12.4      13.5  2.4300  1.2690
156   Smelt    12.2    13.0      13.8  2.2770  1.2558
157   Smelt    19.7    14.3      15.2  2.8728  2.0672
158   Smelt    19.9    15.0      16.2  2.9322  1.8792


In [2]:
print(pd.unique(fish["Species"])) # 종 출력

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


## **데이터 분리, 정규화**

In [5]:
df=fish.drop(['Species'], axis=1)
fish_input=df.to_numpy()
fish_target=fish['Species'].to_numpy()

In [6]:
# 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    fish_input, fish_target, random_state=42
)

# 정규화
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(X_train)
X_train=ss.transform(X_train)
X_test=ss.transform(X_test)

## **Logistic Regression**

In [7]:
# 다중회귀 로지스틱 
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
# C, max_iter: 규제값과 반복횟수 # C가 클수록 규제 완화
lr.fit(X_train, y_train)
print("훈련 성능: ", lr.score(X_train, y_train))
print("테스트 성능 ", lr.score(X_test, y_test))

훈련 성능:  0.9327731092436975
테스트 성능  0.925


In [8]:
# 계수와 상수 관찰
print("계수, 상수: ", lr.coef_.shape, lr.intercept_.shape)

계수, 상수:  (7, 5) (7,)


## **Probability bj softmax**

In [9]:
# 확률 예측
prob_pred=lr.predict_proba(X_test[:5])
print("내장함수 predict_proba를 통한 확률계산")
print(np.round(prob_pred, decimals=3))

내장함수 predict_proba를 통한 확률계산
[[0.    0.014 0.841 0.    0.136 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.935 0.015 0.016 0.   ]
 [0.011 0.034 0.306 0.007 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]


In [10]:
# 다중회귀 z값 출력
decision=lr.decision_function(X_test[:5])
print("다중회귀 z값 출력")
print(np.round(decision, decimals=2))

다중회귀 z값 출력
[[ -6.5    1.03   5.16  -2.73   3.34   0.33  -0.63]
 [-10.86   1.93   4.77  -2.4    2.98   7.84  -4.26]
 [ -4.34  -6.23   3.17   6.49   2.36   2.42  -3.87]
 [ -0.68   0.45   2.65  -1.19   3.26  -5.75   1.26]
 [ -6.4   -1.99   5.82  -0.11   3.5   -0.11  -0.71]]


In [11]:
# softmax 함수 계산으로 확률예측과 일치하는지 확인
from scipy.special import softmax
prob_softmax=softmax(decision, axis=1) # 각 행에 대한 softmax 계산 
print("softmax 함수를 통한 확률계산")
print(np.round(prob_softmax, decimals=3))

softmax 함수를 통한 확률계산
[[0.    0.014 0.841 0.    0.136 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.935 0.015 0.016 0.   ]
 [0.011 0.034 0.306 0.007 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
